usethis::use_testthat()
usethis::use_tibble()
usethis::use_roxygen_md()
usethis::use_readme_rmd()
usethis::use_news_md()
usethis::use_lifecycle()
usethis::use_lifecycle_badge("experimental")
usethis::use_mit_license("CorradoLanera")
usethis::use_code_of_conduct("Corrado.Lanera@gmail.com")
usethis::use_spell_check()
usethis::use_git()
usethis::git_vaccinate()
usethis::use_github(organisation = "CorradoLanera", protocol = "ssh")
usethis::use_coverage(repo_spec = "CorradoLanera/gpteasyr")
usethis::use_github_action("test-coverage", badge = TRUE)
usethis::use_github_action("check-standard", badge = TRUE)


usethis::use_package("checkmate", type = "Suggests")
usethis::use_package("lintr", type = "Suggests")
usethis::use_package("withr", type = "Suggests")
usethis::use_tidy_description()

usethis::use_pkgdown_github_pages()
