usethis::use_testthat()
usethis::use_tibble()
usethis::use_roxygen_md()
usethis::use_readme_rmd()
usethis::use_news_md()
usethis::use_lifecycle()
usethis::use_lifecycle_badge("experimental")
usethis::use_mit_license("CorradoLanera")
usethis::use_code_of_conduct("Corrado.Lanera@ubep.unipd.it")
usethis::use_tidy_description()
usethis::use_spell_check()
usethis::use_git()
usethis::git_vaccinate()
usethis::use_github(organisation = "UBESP-DCTV", protocol = "ssh")
usethis::use_coverage()
usethis::use_github_action("test-coverage", badge = TRUE)
usethis::use_github_action("check-standard", badge = TRUE)
